apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=catalog-db;Port=5432;Database=catalog;Username=catalog;Password=catalog"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
  JwtSettings__SecurityKey: "FcgCatalog_Secret_Key_2026_High_Security_Token"
